"""member speak_country_id, character_id nullable

Revision ID: 0639d3d1a7fc
Revises: 781e55e51986
Create Date: 2026-06-22 22:40:01.007907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0639d3d1a7fc'
down_revision: Union[str, Sequence[str], None] = '781e55e51986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'speak_country_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='억양')
    op.alter_column('member', 'character_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='대표 캐릭터')
    op.drop_constraint(op.f('member_character_id_fkey'), 'member', type_='foreignkey')
    op.drop_constraint(op.f('member_speak_country_id_fkey'), 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'speak_country', ['speak_country_id'], ['speak_country_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'member', 'character', ['character_id'], ['character_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key(op.f('member_speak_country_id_fkey'), 'member', 'speak_country', ['speak_country_id'], ['speak_country_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('member_character_id_fkey'), 'member', 'character', ['character_id'], ['character_id'], ondelete='RESTRICT')
    op.alter_column('member', 'character_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='대표 캐릭터')
    op.alter_column('member', 'speak_country_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='억양')
    # ### end Alembic commands ###
