"""email nullable + social unique

Revision ID: 0bd2cfdb168e
Revises: 0639d3d1a7fc
Create Date: 2026-06-22 22:49:12.451908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd2cfdb168e'
down_revision: Union[str, Sequence[str], None] = '0639d3d1a7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'email',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='이메일(소셜은 없을 수 있음)',
               existing_comment='이메일')
    op.create_unique_constraint('uq_member_social', 'member', ['login_method', 'unique_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_member_social', 'member', type_='unique')
    op.alter_column('member', 'email',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='이메일',
               existing_comment='이메일(소셜은 없을 수 있음)')
    # ### end Alembic commands ###
