"""initial 14 tables

Revision ID: 781e55e51986
Revises: 
Create Date: 2026-06-22 22:13:22.694690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781e55e51986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('character_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True, comment='생성용 프롬프트'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='캐릭터 목소리 URL'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='가격(달러)'),
    sa.Column('name', sa.Text(), nullable=False, comment='캐릭터 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='세부 설명'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='캐릭터 이미지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True, comment='총 점수'),
    sa.Column('pronunciation', sa.Integer(), nullable=True, comment='발음'),
    sa.Column('fluency', sa.Integer(), nullable=True, comment='유창성'),
    sa.Column('rhythm', sa.Integer(), nullable=True, comment='리듬'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('speak_country',
    sa.Column('speak_country_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('first_country', sa.Text(), nullable=True, comment='1순위 국가'),
    sa.Column('second_country', sa.Text(), nullable=True, comment='2순위 국가'),
    sa.Column('third_country', sa.Text(), nullable=True, comment='3순위 국가'),
    sa.Column('first_percent', sa.Integer(), nullable=True, comment='1순위 %'),
    sa.Column('second_percent', sa.Integer(), nullable=True, comment='2순위 %'),
    sa.Column('third_percent', sa.Integer(), nullable=True, comment='3순위 %'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('speak_country_id')
    )
    op.create_table('discount_event',
    sa.Column('discount_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='대상 캐릭터'),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='할인된 가격'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='시작 시간'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='끝나는 시간'),
    sa.Column('activate', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discount_event_id')
    )
    op.create_index(op.f('ix_discount_event_character_id'), 'discount_event', ['character_id'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('speak_country_id', sa.BigInteger(), nullable=False, comment='억양'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='대표 캐릭터'),
    sa.Column('language', sa.Text(), nullable=True, comment='사용 언어'),
    sa.Column('login_method', sa.Text(), nullable=True, comment='로그인 방법'),
    sa.Column('unique_value', sa.Text(), nullable=True, comment='소셜 유니크 번호'),
    sa.Column('email', sa.Text(), nullable=False, comment='이메일'),
    sa.Column('password', sa.Text(), nullable=True, comment='비밀번호(해시 저장 권장)'),
    sa.Column('is_auto_payment', sa.Boolean(), nullable=True, comment='정기구독 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['speak_country_id'], ['speak_country.speak_country_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_member_character_id'), 'member', ['character_id'], unique=False)
    op.create_index(op.f('ix_member_speak_country_id'), 'member', ['speak_country_id'], unique=False)
    op.create_index(op.f('ix_member_unique_value'), 'member', ['unique_value'], unique=False)
    op.create_table('alarm',
    sa.Column('alarm_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='캐릭터'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True, comment='알람 시간'),
    sa.Column('is_activate', sa.Boolean(), nullable=True, comment='활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    op.create_index(op.f('ix_alarm_character_id'), 'alarm', ['character_id'], unique=False)
    op.create_index(op.f('ix_alarm_member_id'), 'alarm', ['member_id'], unique=False)
    op.create_table('call',
    sa.Column('call_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='캐릭터'),
    sa.Column('call_date', sa.DateTime(timezone=True), nullable=True, comment='전화 날짜'),
    sa.Column('total_time', sa.Integer(), nullable=True, comment='총 통화 시간(초)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='대화 내용 한 줄 요약'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='만족도(1~3점)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_call_character_id'), 'call', ['character_id'], unique=False)
    op.create_index('ix_call_member_date', 'call', ['member_id', 'call_date'], unique=False)
    op.create_index(op.f('ix_call_member_id'), 'call', ['member_id'], unique=False)
    op.create_table('member_character',
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='구매한 사람'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='구매한 캐릭터'),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='실제 구매한 가격'),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True, comment='구매한 날짜'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'character_id')
    )
    op.create_index(op.f('ix_member_character_character_id'), 'member_character', ['character_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='결제 날짜'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='결제 금액'),
    sa.Column('description', sa.Text(), nullable=True, comment='결제 내용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_member_id'), 'payment', ['member_id'], unique=False)
    op.create_table('subscribe',
    sa.Column('subscribe_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='시작(결제) 날짜'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='끝나는 날짜'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='결제 금액'),
    sa.Column('is_activate', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscribe_id')
    )
    op.create_index(op.f('ix_subscribe_member_id'), 'subscribe', ['member_id'], unique=False)
    op.create_table('call_raw_data',
    sa.Column('call_raw_data_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False, comment='통화'),
    sa.Column('content', sa.Text(), nullable=True, comment='음성 데이터 전사'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('total_time', sa.Integer(), nullable=True, comment='음성 시간(초)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['call_id'], ['call.call_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_raw_data_id')
    )
    op.create_index(op.f('ix_call_raw_data_call_id'), 'call_raw_data', ['call_id'], unique=False)
    op.create_table('schedule',
    sa.Column('schedule_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alarm_id', sa.BigInteger(), nullable=False, comment='알람'),
    sa.Column('day_of_week', sa.Text(), nullable=True, comment='요일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.alarm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedule_alarm_id'), 'schedule', ['alarm_id'], unique=False)
    op.create_table('sentence',
    sa.Column('sentence_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False, comment='통화'),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False, comment='평가'),
    sa.Column('korean_sentence', sa.Text(), nullable=True, comment='한국어 문장'),
    sa.Column('native_sentence', sa.Text(), nullable=True, comment='모국어 문장'),
    sa.Column('locale', sa.Text(), nullable=True, comment='언어'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True, comment='북마크 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['call_id'], ['call.call_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    op.create_index(op.f('ix_sentence_call_id'), 'sentence', ['call_id'], unique=False)
    op.create_index(op.f('ix_sentence_evaluation_id'), 'sentence', ['evaluation_id'], unique=False)
    op.create_table('review',
    sa.Column('review_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=False, comment='발화'),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=True, comment='기록 시간'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_sentence_id'), 'review', ['sentence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_sentence_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_sentence_evaluation_id'), table_name='sentence')
    op.drop_index(op.f('ix_sentence_call_id'), table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_schedule_alarm_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_call_raw_data_call_id'), table_name='call_raw_data')
    op.drop_table('call_raw_data')
    op.drop_index(op.f('ix_subscribe_member_id'), table_name='subscribe')
    op.drop_table('subscribe')
    op.drop_index(op.f('ix_payment_member_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_member_character_character_id'), table_name='member_character')
    op.drop_table('member_character')
    op.drop_index(op.f('ix_call_member_id'), table_name='call')
    op.drop_index('ix_call_member_date', table_name='call')
    op.drop_index(op.f('ix_call_character_id'), table_name='call')
    op.drop_table('call')
    op.drop_index(op.f('ix_alarm_member_id'), table_name='alarm')
    op.drop_index(op.f('ix_alarm_character_id'), table_name='alarm')
    op.drop_table('alarm')
    op.drop_index(op.f('ix_member_unique_value'), table_name='member')
    op.drop_index(op.f('ix_member_speak_country_id'), table_name='member')
    op.drop_index(op.f('ix_member_character_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_discount_event_character_id'), table_name='discount_event')
    op.drop_table('discount_event')
    op.drop_table('speak_country')
    op.drop_table('evaluation')
    op.drop_table('character')
    # ### end Alembic commands ###
