"""initial schema (supabase auth)

Revision ID: 8390e67d05bd
Revises: 
Create Date: 2026-06-25 16:31:13.714314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8390e67d05bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('level_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('level_no', sa.Integer(), nullable=False, comment='레벨 번호(1~12)'),
    sa.Column('band', sa.Text(), nullable=True, comment='밴드(초급/중급/고급)'),
    sa.Column('grade', sa.Text(), nullable=True, comment='어휘 등급(A/B/C)'),
    sa.Column('stage_name', sa.Text(), nullable=True, comment='단계명(초급 1 …)'),
    sa.Column('textbook', sa.Text(), nullable=True, comment='교재명(Basic Korean A …)'),
    sa.Column('grammar_count', sa.Integer(), nullable=True, comment='문법 포인트 수'),
    sa.Column('vocab_count', sa.Integer(), nullable=True, comment='어휘 수'),
    sa.Column('grammar_scope', sa.Text(), nullable=True, comment='핵심 문법(JSON 배열 문자열)'),
    sa.Column('vocab_sample', sa.Text(), nullable=True, comment='고빈도 대표 어휘(JSON 배열 문자열)'),
    sa.Column('profile', sa.Text(), nullable=True, comment='발화 프로파일(프롬프트 [학습자 수준] 슬롯 주입)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_no', name='uq_level_no')
    )
    op.create_table('speak_country',
    sa.Column('speak_country_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('first_country', sa.Text(), nullable=True, comment='1순위 국가'),
    sa.Column('second_country', sa.Text(), nullable=True, comment='2순위 국가'),
    sa.Column('third_country', sa.Text(), nullable=True, comment='3순위 국가'),
    sa.Column('first_percent', sa.Integer(), nullable=True, comment='1순위 %'),
    sa.Column('second_percent', sa.Integer(), nullable=True, comment='2순위 %'),
    sa.Column('third_percent', sa.Integer(), nullable=True, comment='3순위 %'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('speak_country_id')
    )
    op.create_table('voice',
    sa.Column('voice_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False, comment='Gemini Live 프리빌트 보이스명(예: Charon, Aoede)'),
    sa.Column('description', sa.Text(), nullable=True, comment='음색 설명(예: 밝은/차분한)'),
    sa.Column('gender', sa.Text(), nullable=True, comment='성별 느낌(male/female/neutral)'),
    sa.Column('sample_url', sa.Text(), nullable=True, comment='미리듣기 샘플 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('voice_id'),
    sa.UniqueConstraint('name', name='uq_voice_name')
    )
    op.create_table('character',
    sa.Column('character_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('voice_id', sa.BigInteger(), nullable=True, comment='실시간 통화 음성(Gemini Live voice)'),
    sa.Column('role', sa.Text(), nullable=True, comment='역할/정체성'),
    sa.Column('personality', sa.Text(), nullable=True, comment='성격·말투·톤'),
    sa.Column('rules', sa.Text(), nullable=True, comment='캐릭터별 추가 규칙/금기'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='캐릭터 프리뷰 샘플 음성 URL'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='가격(달러)'),
    sa.Column('name', sa.Text(), nullable=False, comment='캐릭터 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='세부 설명'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='캐릭터 이미지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.voice_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_index(op.f('ix_character_voice_id'), 'character', ['voice_id'], unique=False)
    op.create_table('discount_event',
    sa.Column('discount_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='대상 캐릭터'),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='할인된 가격'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='시작 시간'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='끝나는 시간'),
    sa.Column('activate', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discount_event_id')
    )
    op.create_index(op.f('ix_discount_event_character_id'), 'discount_event', ['character_id'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('auth_user_id', sa.Text(), nullable=True, comment='Supabase auth.users.id (UUID)'),
    sa.Column('speak_country_id', sa.BigInteger(), nullable=True, comment='억양'),
    sa.Column('character_id', sa.BigInteger(), nullable=True, comment='대표 캐릭터'),
    sa.Column('name', sa.Text(), nullable=True, comment='이름(온보딩에서 입력)'),
    sa.Column('language', sa.Text(), nullable=True, comment='모국어(번역 target locale)'),
    sa.Column('email', sa.Text(), nullable=True, comment='이메일(Supabase 에서 동기화)'),
    sa.Column('is_auto_payment', sa.Boolean(), nullable=True, comment='정기구독 여부'),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='온보딩(이름·학습이유·언어) 완료 여부'),
    sa.Column('korean_level', sa.Integer(), nullable=True, comment='한국어 레벨(1~12 → level.level_no)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speak_country_id'], ['speak_country.speak_country_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_member_auth_user_id'), 'member', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_member_character_id'), 'member', ['character_id'], unique=False)
    op.create_index(op.f('ix_member_speak_country_id'), 'member', ['speak_country_id'], unique=False)
    op.create_table('alarm',
    sa.Column('alarm_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='캐릭터'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True, comment='알람 시간'),
    sa.Column('is_activate', sa.Boolean(), nullable=True, comment='활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    op.create_index(op.f('ix_alarm_character_id'), 'alarm', ['character_id'], unique=False)
    op.create_index(op.f('ix_alarm_member_id'), 'alarm', ['member_id'], unique=False)
    op.create_table('call',
    sa.Column('call_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='캐릭터'),
    sa.Column('call_date', sa.DateTime(timezone=True), nullable=True, comment='전화 날짜'),
    sa.Column('total_time', sa.Integer(), nullable=True, comment='총 통화 시간(초)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='대화 내용 한 줄 요약'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='만족도(1~3점)'),
    sa.Column('status', sa.Text(), server_default=sa.text("'ongoing'"), nullable=False, comment='분석 상태(ongoing/analyzing/done/failed)'),
    sa.Column('mode', sa.Text(), nullable=True, comment='감지된 통화 모드(conversation/study/unknown)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_call_character_id'), 'call', ['character_id'], unique=False)
    op.create_index('ix_call_member_date', 'call', ['member_id', 'call_date'], unique=False)
    op.create_index(op.f('ix_call_member_id'), 'call', ['member_id'], unique=False)
    op.create_table('member_character',
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='구매한 사람'),
    sa.Column('character_id', sa.BigInteger(), nullable=False, comment='구매한 캐릭터'),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='실제 구매한 가격'),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True, comment='구매한 날짜'),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'character_id')
    )
    op.create_index(op.f('ix_member_character_character_id'), 'member_character', ['character_id'], unique=False)
    op.create_table('member_reason',
    sa.Column('member_reason_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False, comment='학습 이유 코드'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_reason_id'),
    sa.UniqueConstraint('member_id', 'reason', name='uq_member_reason')
    )
    op.create_index(op.f('ix_member_reason_member_id'), 'member_reason', ['member_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='결제 날짜'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='결제 금액'),
    sa.Column('description', sa.Text(), nullable=True, comment='결제 내용'),
    sa.Column('category', sa.Text(), nullable=True, comment='결제 분류(subscribe/character)'),
    sa.Column('card_info', sa.Text(), nullable=True, comment='카드 정보(마스킹)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_category'), 'payment', ['category'], unique=False)
    op.create_index(op.f('ix_payment_member_id'), 'payment', ['member_id'], unique=False)
    op.create_table('subscribe',
    sa.Column('subscribe_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='회원'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='시작(결제) 날짜'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='끝나는 날짜'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='결제 금액'),
    sa.Column('is_activate', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscribe_id')
    )
    op.create_index(op.f('ix_subscribe_member_id'), 'subscribe', ['member_id'], unique=False)
    op.create_table('call_raw_data',
    sa.Column('call_raw_data_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False, comment='통화'),
    sa.Column('role', sa.Text(), nullable=True, comment='화자(user/beaver)'),
    sa.Column('turn_index', sa.Integer(), nullable=True, comment='턴 순서(0부터)'),
    sa.Column('content', sa.Text(), nullable=True, comment='음성 데이터 전사'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('total_time', sa.Integer(), nullable=True, comment='음성 시간(초)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['call_id'], ['call.call_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_raw_data_id')
    )
    op.create_index(op.f('ix_call_raw_data_call_id'), 'call_raw_data', ['call_id'], unique=False)
    op.create_table('schedule',
    sa.Column('schedule_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alarm_id', sa.BigInteger(), nullable=False, comment='알람'),
    sa.Column('day_of_week', sa.Text(), nullable=True, comment='요일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.alarm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedule_alarm_id'), 'schedule', ['alarm_id'], unique=False)
    op.create_table('sentence',
    sa.Column('sentence_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False, comment='통화'),
    sa.Column('korean_sentence', sa.Text(), nullable=True, comment='한국어 문장'),
    sa.Column('native_sentence', sa.Text(), nullable=True, comment='모국어 문장'),
    sa.Column('locale', sa.Text(), nullable=True, comment='언어'),
    sa.Column('source_type', sa.Text(), nullable=True, comment='표현 출처(asked/corrected/drilled)'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True, comment='북마크 여부'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='소프트 삭제 시각(NULL=정상)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['call_id'], ['call.call_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    op.create_index(op.f('ix_sentence_call_id'), 'sentence', ['call_id'], unique=False)
    op.create_index(op.f('ix_sentence_deleted_at'), 'sentence', ['deleted_at'], unique=False)
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=False, comment='발화'),
    sa.Column('total_score', sa.Integer(), nullable=True, comment='총 점수'),
    sa.Column('pronunciation', sa.Integer(), nullable=True, comment='발음'),
    sa.Column('fluency', sa.Integer(), nullable=True, comment='유창성'),
    sa.Column('rhythm', sa.Integer(), nullable=True, comment='리듬'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id'),
    sa.UniqueConstraint('sentence_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=False, comment='발화'),
    sa.Column('voice_url', sa.Text(), nullable=True, comment='보이스 데이터 저장 위치'),
    sa.Column('feedback', sa.JSON(), nullable=True, comment='채점 결과(평가 점수 + 글자별 상/중/하)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_sentence_id'), 'review', ['sentence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_sentence_id'), table_name='review')
    op.drop_table('review')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_sentence_deleted_at'), table_name='sentence')
    op.drop_index(op.f('ix_sentence_call_id'), table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_schedule_alarm_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_call_raw_data_call_id'), table_name='call_raw_data')
    op.drop_table('call_raw_data')
    op.drop_index(op.f('ix_subscribe_member_id'), table_name='subscribe')
    op.drop_table('subscribe')
    op.drop_index(op.f('ix_payment_member_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_category'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_member_reason_member_id'), table_name='member_reason')
    op.drop_table('member_reason')
    op.drop_index(op.f('ix_member_character_character_id'), table_name='member_character')
    op.drop_table('member_character')
    op.drop_index(op.f('ix_call_member_id'), table_name='call')
    op.drop_index('ix_call_member_date', table_name='call')
    op.drop_index(op.f('ix_call_character_id'), table_name='call')
    op.drop_table('call')
    op.drop_index(op.f('ix_alarm_member_id'), table_name='alarm')
    op.drop_index(op.f('ix_alarm_character_id'), table_name='alarm')
    op.drop_table('alarm')
    op.drop_index(op.f('ix_member_speak_country_id'), table_name='member')
    op.drop_index(op.f('ix_member_character_id'), table_name='member')
    op.drop_index(op.f('ix_member_auth_user_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_discount_event_character_id'), table_name='discount_event')
    op.drop_table('discount_event')
    op.drop_index(op.f('ix_character_voice_id'), table_name='character')
    op.drop_table('character')
    op.drop_table('voice')
    op.drop_table('speak_country')
    op.drop_table('level')
    # ### end Alembic commands ###
