"""payment category, card_info

Revision ID: c4ef76897492
Revises: 0bd2cfdb168e
Create Date: 2026-06-22 23:22:09.221001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ef76897492'
down_revision: Union[str, Sequence[str], None] = '0bd2cfdb168e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('category', sa.Text(), nullable=True, comment='결제 분류(subscribe/character)'))
    op.add_column('payment', sa.Column('card_info', sa.Text(), nullable=True, comment='카드 정보(마스킹)'))
    op.create_index(op.f('ix_payment_category'), 'payment', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_category'), table_name='payment')
    op.drop_column('payment', 'card_info')
    op.drop_column('payment', 'category')
    # ### end Alembic commands ###
