"""review feedback json

Revision ID: ed3b49db0197
Revises: c4ef76897492
Create Date: 2026-06-22 23:58:36.627464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3b49db0197'
down_revision: Union[str, Sequence[str], None] = 'c4ef76897492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('feedback', sa.JSON(), nullable=True, comment='채점 결과(평가 점수 + 글자별 상/중/하)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'feedback')
    # ### end Alembic commands ###
